In [1]:
import pandas as pd

In [21]:
with open('apple-2024.pdf_balance_sheet.tsv', 'r') as f:
    data_2024 = f.read()
with open('apple-2022.pdf_balance_sheet.tsv', 'r') as f:
    data_2022 = f.read()
with open('apple-2020.pdf_balance_sheet.tsv', 'r') as f:
    data_2020 = f.read()
with open('apple-2018.pdf_balance_sheet.tsv', 'r') as f:
    data_2018 = f.read()

In [14]:
data

"Balance Sheet\nItem\tCategory\tSubcategory\tSeptember 29, 2018\tSeptember 30, 2017\nAssets\tCurrent Assets\tCash and cash equivalents\t25913\t20289\nAssets\tCurrent Assets\tMarketable securities\t40388\t53892\nAssets\tCurrent Assets\tAccounts receivable, net\t23186\t17874\nAssets\tCurrent Assets\tInventories\t3956\t4855\nAssets\tCurrent Assets\tVendor non-trade receivables\t25809\t17799\nAssets\tCurrent Assets\tOther current assets\t12087\t13936\nAssets\tNon-current Assets\tMarketable securities\t170799\t194714\nAssets\tNon-current Assets\tProperty, plant and equipment, net\t41304\t33783\nAssets\tNon-current Assets\tOther non-current assets\t22283\t18177\nLiabilities and Shareholders’ Equity\tCurrent Liabilities\tAccounts payable\t55888\t44242\nLiabilities and Shareholders’ Equity\tCurrent Liabilities\tOther current liabilities\t32687\t30551\nLiabilities and Shareholders’ Equity\tCurrent Liabilities\tDeferred revenue\t7543\t7548\nLiabilities and Shareholders’ Equity\tCurrent Liabilities\tCommercial paper\t11964\t11977\nLiabilities and Shareholders’ Equity\tCurrent Liabilities\tTerm debt\t8784\t6496\nLiabilities and Shareholders’ Equity\tNon-current Liabilities\tDeferred revenue\t2797\t2836\nLiabilities and Shareholders’ Equity\tNon-current Liabilities\tTerm debt\t93735\t97207\nLiabilities and Shareholders’ Equity\tNon-current Liabilities\tOther non-current liabilities\t45180\t40415\nLiabilities and Shareholders’ Equity\tShareholders’ Equity\tCommon stock and additional paid-in capital\t40201\t35867\nLiabilities and Shareholders’ Equity\tShareholders’ Equity\tRetained earnings\t70400\t98330\nLiabilities and Shareholders’ Equity\tShareholders’ Equity\tAccumulated other comprehensive income/(loss)\t-3454\t-150\n\nStatement of Operations\nItem\tCategory\tSubcategory\tSeptember 29, 2018\tSeptember 30, 2017\tSeptember 24, 2016\nNet sales\tnull\tnull\t265595\t229234\t215639\nCost of sales\tnull\tnull\t163756\t141048\t131376\nGross margin\tnull\tnull\t101839\t88186\t84263\nOperating expenses\tnull\tResearch and development\t14236\t11581\t10045\nOperating expenses\tnull\tSelling, general and administrative\t16705\t15261\t14194\nTotal operating expenses\tnull\tnull\t30941\t26842\t24239\nOperating income\tnull\tnull\t70898\t61344\t60024\nOther income/(expense), net\tnull\tnull\t2005\t2745\t1348\nIncome before provision for income taxes\tnull\tnull\t72903\t64089\t61372\nProvision for income taxes\tnull\tnull\t13372\t15738\t15685\nNet income\tnull\tnull\t59531\t48351\t45687\n\nCash Flow\nItem\tCategory\tSubcategory\tSeptember 29, 2018\tSeptember 30, 2017\tSeptember 24, 2016\nCash and cash equivalents, beginning of the year\tOperating Activities\tnull\t20289\t20484\t21120\nNet income\tOperating Activities\tnull\t59531\t48351\t45687\nDepreciation and amortization\tOperating Activities\tnull\t10903\t10157\t10505\nShare-based compensation expense\tOperating Activities\tnull\t5340\t4840\t4210\nDeferred income tax expense/(benefit)\tOperating Activities\tnull\t-32590\t5966\t4938\nOther\tOperating Activities\tnull\t-444\t-166\t486\nCash generated by operating activities\tOperating Activities\tnull\t77434\t64225\t66231\nCash generated by/(used in) investing activities\tInvesting Activities\tnull\t16066\t-46446\t-45977\nCash used in financing activities\tFinancing Activities\tnull\t-87876\t-17974\t-20890\nIncrease/(Decrease) in cash and cash equivalents\tnull\tnull\t5624\t-195\t-636\nCash and cash equivalents, end of the year\tnull\tnull\t25913\t20289\t20484\n\nShareholder's Equity\nItem\tCategory\tSubcategory\tSeptember 29, 2018\tSeptember 30, 2017\tSeptember 24, 2016\nCommon Stock and Additional Paid-In Capital\tnull\tShares\t4754986\t5126201\t5336166\nCommon Stock and Additional Paid-In Capital\tnull\tAmount\t40201\t35867\t31251\nRetained Earnings\tnull\tnull\t70400\t98330\t96364\nAccumulated Other Comprehensive Income/(Loss)\tnull\tnull\t-3454\t-150\t634\nTotal Shareholders’ Equity\tnull\tnull\t107147\t134047\t128249"

In [36]:
from io import StringIO
sections2024 = data_2024.split("\n\n")
sections2022 = data_2022.split("\n\n")
sections2020 = data_2020.split("\n\n")
sections2018 = data_2018.split("\n\n")

# Extract Balance Sheet
balance_sheet_data_2024 = sections2024[0]
balance_sheet_df_2024 = pd.read_csv(StringIO(balance_sheet_data_2024), sep="\t",skiprows=1)
balance_sheet_data_2022 = sections2022[0]
balance_sheet_df_2022 = pd.read_csv(StringIO(balance_sheet_data_2022), sep="\t",skiprows=1)
balance_sheet_data_2020 = sections2020[0]
balance_sheet_df_2020 = pd.read_csv(StringIO(balance_sheet_data_2020), sep="\t",skiprows=1)
balance_sheet_data_2018 = sections2018[0]
balance_sheet_df_2018 = pd.read_csv(StringIO(balance_sheet_data_2018), sep="\t",skiprows=1)
# # Extract Statement of Operations
# operations_data = sections[1]
# operations_df = pd.read_csv(StringIO(operations_data), sep="\t")

# # Extract Cash Flow
# cash_flow_data = sections[2]
# cash_flow_df = pd.read_csv(StringIO(cash_flow_data), sep="\t")

# # Displaying the DataFrames
# print("Balance Sheet DataFrame:")
# print(balance_sheet_df.head())
# print("\nStatement of Operations DataFrame:")
# print(operations_df.head())
# print("\nCash Flow DataFrame:")
# print(cash_flow_df.head())

In [37]:
balance_sheet_df_2024

,Item,Category,Subcategory,2024-09-28,2023-09-30
0,Assets,CurrentAssets,Cash and cash equivalents,29943,29965
1,Assets,CurrentAssets,Marketable securities,35228,31590
2,Assets,CurrentAssets,"Accounts receivable, net",33410,29508
3,Assets,CurrentAssets,Vendor non-trade receivables,32833,31477
4,Assets,CurrentAssets,Inventories,7286,6331
5,Assets,CurrentAssets,Other current assets,14287,14695
6,Assets,CurrentAssets,Total current assets,152987,143566
7,Assets,NonCurrentAssets,Marketable securities,91479,100544
8,Assets,NonCurrentAssets,"Property, plant and equipment, net",45680,43715
9,Assets,NonCurrentAssets,Other non-current assets,74834,64758
10,Assets,NonCurrentAssets,Total non-current assets,211993,209017
11,Assets,Total assets,NaN,364980,352583
12,LiabilitiesAndShareholdersEquity,CurrentLiabilities,Accounts payable,68960,62611
13,LiabilitiesAndShareholdersEquity,CurrentLiabilities,Other current liabilities,78304,58829
14,LiabilitiesAndShareholdersEquity,CurrentLiabilities,Deferred revenue,8249,8061
15,LiabilitiesAndShareholdersEquity,CurrentLiabilities,Commercial paper,9967,5985
16,LiabilitiesAndShareholdersEquity,CurrentLiabilities,Term debt,10912,9822
17,LiabilitiesAndShareholdersEquity,CurrentLiabilities,Total current liabilities,176392,145308
18,LiabilitiesAndShareholdersEquity,NonCurrentLiabilities,Term debt,85750,95281
19,LiabilitiesAndShareholdersEquity,NonCurrentLiabilities,Other non-current liabilities,45888,49848
20,LiabilitiesAndShareholdersEquity,NonCurrentLiabilities,Total non-current liabilities,131638,145129
21,LiabilitiesAndShareholdersEquity,ShareholdersEquity,Common stock and additional paid-in capital,83276,73812
22,LiabilitiesAndShareholdersEquity,ShareholdersEquity,Accumulated deficit,-19154,-214
23,LiabilitiesAndShareholdersEquity,ShareholdersEquity,Accumulated other comprehensive loss,-7172,-11452
24,LiabilitiesAndShareholdersEquity,ShareholdersEquity,Total shareholders’ equity,56950,62146
25,LiabilitiesAndShareholdersEquity,Total liabilities and shareholders’ equity,NaN,364980,352583

In [44]:

balance_sheet_df_2022

,Item,Category,Subcategory,"September 24, 2022","September 25, 2021"
0,ASSETS,Current assets,Cash and cash equivalents,23646,34940
1,ASSETS,Current assets,Marketable securities,2458,27699
2,ASSETS,Current assets,"Accounts receivable, net",28184,26278
3,ASSETS,Current assets,Inventories,4946,6580
4,ASSETS,Current assets,Vendor non-trade receivables,32748,25228
5,ASSETS,Current assets,Other current assets,21223,14111
6,ASSETS,Current assets,Total current assets,135405,134836
7,ASSETS,Non-current assets,Marketable securities,120805,127877
8,ASSETS,Non-current assets,"Property, plant and equipment, net",42117,39440
9,ASSETS,Non-current assets,Other non-current assets,54428,48849
10,ASSETS,Non-current assets,Total non-current assets,217350,216166
11,ASSETS,Total assets,NaN,352755,351002
12,LIABILITIES AND SHAREHOLDERS’ EQUITY,Current liabilities,Accounts payable,64115,54763
13,LIABILITIES AND SHAREHOLDERS’ EQUITY,Current liabilities,Other current liabilities,60845,47493
14,LIABILITIES AND SHAREHOLDERS’ EQUITY,Current liabilities,Deferred revenue,7912,7612
15,LIABILITIES AND SHAREHOLDERS’ EQUITY,Current liabilities,Commercial paper,9982,6000
16,LIABILITIES AND SHAREHOLDERS’ EQUITY,Current liabilities,Term debt,11128,9613
17,LIABILITIES AND SHAREHOLDERS’ EQUITY,Current liabilities,Total current liabilities,153982,125481
18,LIABILITIES AND SHAREHOLDERS’ EQUITY,Non-current liabilities,Term debt,98959,109106
19,LIABILITIES AND SHAREHOLDERS’ EQUITY,Non-current liabilities,Other non-current liabilities,49142,53325
20,LIABILITIES AND SHAREHOLDERS’ EQUITY,Non-current liabilities,Total non-current liabilities,148101,162431
21,LIABILITIES AND SHAREHOLDERS’ EQUITY,Total liabilities,NaN,302083,287912
22,LIABILITIES AND SHAREHOLDERS’ EQUITY,Shareholders’ equity,Common stock and additional paid-in capital,64849,57365
23,LIABILITIES AND SHAREHOLDERS’ EQUITY,Shareholders’ equity,Retained earnings/(Accumulated deficit),-3068,5562
24,LIABILITIES AND SHAREHOLDERS’ EQUITY,Shareholders’ equity,Accumulated other comprehensive income/(loss),-11109,163
25,LIABILITIES AND SHAREHOLDERS’ EQUITY,Shareholders’ equity,Total shareholders’ equity,50672,63090
26,LIABILITIES AND SHAREHOLDERS’ EQUITY,Total liabilities and shareholders’ equity,NaN,352755,351002

In [39]:

balance_sheet_df_2020

,Item,Category,Subcategory,2020-09-26,2019-09-28
0,Assets,Current Assets,Cash and Cash Equivalents,38016,48844
1,Assets,Current Assets,Marketable Securities,52927,51713
2,Assets,Current Assets,"Accounts Receivable, net",16120,22926
3,Assets,Current Assets,Inventories,4061,4106
4,Assets,Current Assets,Vendor Non-Trade Receivables,21325,22878
5,Assets,Current Assets,Other Current Assets,11264,12352
6,Assets,Current Assets,Total Current Assets,143713,162819
7,Assets,Non-Current Assets,Marketable Securities,100887,105341
8,Assets,Non-Current Assets,"Property, Plant and Equipment, net",36766,37378
9,Assets,Non-Current Assets,Other Non-Current Assets,42522,32978
10,Assets,Non-Current Assets,Total Non-Current Assets,180175,175697
11,Assets,Total Assets,NaN,323888,338516
12,Liabilities and Shareholders' Equity,Current Liabilities,Accounts Payable,42296,46236
13,Liabilities and Shareholders' Equity,Current Liabilities,Other Current Liabilities,42684,37720
14,Liabilities and Shareholders' Equity,Current Liabilities,Deferred Revenue,6643,5522
15,Liabilities and Shareholders' Equity,Current Liabilities,Commercial Paper,4996,5980
16,Liabilities and Shareholders' Equity,Current Liabilities,Term Debt,8773,10260
17,Liabilities and Shareholders' Equity,Current Liabilities,Total Current Liabilities,105392,105718
18,Liabilities and Shareholders' Equity,Non-Current Liabilities,Term Debt,98667,91807
19,Liabilities and Shareholders' Equity,Non-Current Liabilities,Other Non-Current Liabilities,54490,50503
20,Liabilities and Shareholders' Equity,Non-Current Liabilities,Total Non-Current Liabilities,153157,142310
21,Liabilities and Shareholders' Equity,Total Liabilities,NaN,258549,248028
22,Liabilities and Shareholders' Equity,Shareholders' Equity,Common Stock and Additional Paid-In Capital,50779,45174
23,Liabilities and Shareholders' Equity,Shareholders' Equity,Retained Earnings,14966,45898
24,Liabilities and Shareholders' Equity,Shareholders' Equity,Accumulated Other Comprehensive Income/(Loss),-406,-584
25,Liabilities and Shareholders' Equity,Shareholders' Equity,Total Shareholders' Equity,65339,90488
26,Liabilities and Shareholders' Equity,Total Liabilities and Shareholders' Equity,NaN,323888,338516

In [40]:

balance_sheet_df_2018

,Item,Category,Subcategory,"September 29, 2018","September 30, 2017"
0,Assets,Current Assets,Cash and cash equivalents,25913,20289
1,Assets,Current Assets,Marketable securities,40388,53892
2,Assets,Current Assets,"Accounts receivable, net",23186,17874
3,Assets,Current Assets,Inventories,3956,4855
4,Assets,Current Assets,Vendor non-trade receivables,25809,17799
5,Assets,Current Assets,Other current assets,12087,13936
6,Assets,Non-current Assets,Marketable securities,170799,194714
7,Assets,Non-current Assets,"Property, plant and equipment, net",41304,33783
8,Assets,Non-current Assets,Other non-current assets,22283,18177
9,Liabilities and Shareholders’ Equity,Current Liabilities,Accounts payable,55888,44242
10,Liabilities and Shareholders’ Equity,Current Liabilities,Other current liabilities,32687,30551
11,Liabilities and Shareholders’ Equity,Current Liabilities,Deferred revenue,7543,7548
12,Liabilities and Shareholders’ Equity,Current Liabilities,Commercial paper,11964,11977
13,Liabilities and Shareholders’ Equity,Current Liabilities,Term debt,8784,6496
14,Liabilities and Shareholders’ Equity,Non-current Liabilities,Deferred revenue,2797,2836
15,Liabilities and Shareholders’ Equity,Non-current Liabilities,Term debt,93735,97207
16,Liabilities and Shareholders’ Equity,Non-current Liabilities,Other non-current liabilities,45180,40415
17,Liabilities and Shareholders’ Equity,Shareholders’ Equity,Common stock and additional paid-in capital,40201,35867
18,Liabilities and Shareholders’ Equity,Shareholders’ Equity,Retained earnings,70400,98330
19,Liabilities and Shareholders’ Equity,Shareholders’ Equity,Accumulated other comprehensive income/(loss),-3454,-150

In [41]:
print(len(balance_sheet_df_2024))
print(len(balance_sheet_df_2022))
print(len(balance_sheet_df_2020))
print(len(balance_sheet_df_2018))

26
27
27
20

In [84]:
# balance_sheet_df_2024 = balance_sheet_df_2024['Balance Sheet']  # Assuming actual data starts at row 1
# balance_sheet_df_2022 = balance_sheet_df_2022['Balance Sheet']  # Similarly for the second DataFrame
# Convert column names to lowercase for both dataframes
import string

# Function to clean the text: lowercase, remove spaces, and punctuation
def clean_text(x):
    if isinstance(x, str):
        # Convert to lowercase, remove spaces and punctuation
        return ''.join(e for e in x.lower() if e not in [] and not e.isspace() and e != "’" and e !="'" and e != "-")
    return x
balance_sheet_df_2024 = balance_sheet_df_2024.applymap(clean_text)
balance_sheet_df_2022 = balance_sheet_df_2022.applymap(clean_text)
# balance_sheet_df_2024.columns = balance_sheet_df_2024.columns.str.lower()
# balance_sheet_df_2022.columns = balance_sheet_df_2022.columns.str.lower()
# balance_sheet_df_2024 = balance_sheet_df_2024.applymap(lambda x: x.lower() if isinstance(x, str) else x)
# balance_sheet_df_2022 = balance_sheet_df_2022.applymap(lambda x: x.lower() if isinstance(x, str) else x)
# Now proceed with the merge operation

merged_balance_sheet = balance_sheet_df_2024
merged_balance_sheet = pd.merge(merged_balance_sheet, balance_sheet_df_2022, 
                                on=['item', 'category', 'subcategory'], 
                                suffixes=('_2024', '_2022'))

In [85]:
balance_sheet_df_2024

,item,category,subcategory,2024-09-28,2023-09-30
0,assets,currentassets,cashandcashequivalents,29943,29965
1,assets,currentassets,marketablesecurities,35228,31590
2,assets,currentassets,accountsreceivablenet,33410,29508
3,assets,currentassets,vendornontradereceivables,32833,31477
4,assets,currentassets,inventories,7286,6331
5,assets,currentassets,othercurrentassets,14287,14695
6,assets,currentassets,totalcurrentassets,152987,143566
7,assets,noncurrentassets,marketablesecurities,91479,100544
8,assets,noncurrentassets,propertyplantandequipmentnet,45680,43715
9,assets,noncurrentassets,othernoncurrentassets,74834,64758
10,assets,noncurrentassets,totalnoncurrentassets,211993,209017
11,assets,totalassets,NaN,364980,352583
12,liabilitiesandshareholdersequity,currentliabilities,accountspayable,68960,62611
13,liabilitiesandshareholdersequity,currentliabilities,othercurrentliabilities,78304,58829
14,liabilitiesandshareholdersequity,currentliabilities,deferredrevenue,8249,8061
15,liabilitiesandshareholdersequity,currentliabilities,commercialpaper,9967,5985
16,liabilitiesandshareholdersequity,currentliabilities,termdebt,10912,9822
17,liabilitiesandshareholdersequity,currentliabilities,totalcurrentliabilities,176392,145308
18,liabilitiesandshareholdersequity,noncurrentliabilities,termdebt,85750,95281
19,liabilitiesandshareholdersequity,noncurrentliabilities,othernoncurrentliabilities,45888,49848
20,liabilitiesandshareholdersequity,noncurrentliabilities,totalnoncurrentliabilities,131638,145129
21,liabilitiesandshareholdersequity,shareholdersequity,commonstockandadditionalpaidincapital,83276,73812
22,liabilitiesandshareholdersequity,shareholdersequity,accumulateddeficit,-19154,-214
23,liabilitiesandshareholdersequity,shareholdersequity,accumulatedothercomprehensiveloss,-7172,-11452
24,liabilitiesandshareholdersequity,shareholdersequity,totalshareholdersequity,56950,62146
25,liabilitiesandshareholdersequity,totalliabilitiesandshareholdersequity,NaN,364980,352583

In [86]:
balance_sheet_df_2022['item'][12]

'liabilitiesandshareholdersequity'

In [87]:
merged_balance_sheet

,item,category,subcategory,2024-09-28,2023-09-30,"september 24, 2022","september 25, 2021"
0,assets,currentassets,cashandcashequivalents,29943,29965,23646,34940
1,assets,currentassets,marketablesecurities,35228,31590,2458,27699
2,assets,currentassets,accountsreceivablenet,33410,29508,28184,26278
3,assets,currentassets,vendornontradereceivables,32833,31477,32748,25228
4,assets,currentassets,inventories,7286,6331,4946,6580
5,assets,currentassets,othercurrentassets,14287,14695,21223,14111
6,assets,currentassets,totalcurrentassets,152987,143566,135405,134836
7,assets,noncurrentassets,marketablesecurities,91479,100544,120805,127877
8,assets,noncurrentassets,propertyplantandequipmentnet,45680,43715,42117,39440
9,assets,noncurrentassets,othernoncurrentassets,74834,64758,54428,48849
10,assets,noncurrentassets,totalnoncurrentassets,211993,209017,217350,216166
11,assets,totalassets,NaN,364980,352583,352755,351002
12,liabilitiesandshareholdersequity,currentliabilities,accountspayable,68960,62611,64115,54763
13,liabilitiesandshareholdersequity,currentliabilities,othercurrentliabilities,78304,58829,60845,47493
14,liabilitiesandshareholdersequity,currentliabilities,deferredrevenue,8249,8061,7912,7612
15,liabilitiesandshareholdersequity,currentliabilities,commercialpaper,9967,5985,9982,6000
16,liabilitiesandshareholdersequity,currentliabilities,termdebt,10912,9822,11128,9613
17,liabilitiesandshareholdersequity,currentliabilities,totalcurrentliabilities,176392,145308,153982,125481
18,liabilitiesandshareholdersequity,noncurrentliabilities,termdebt,85750,95281,98959,109106
19,liabilitiesandshareholdersequity,noncurrentliabilities,othernoncurrentliabilities,45888,49848,49142,53325
20,liabilitiesandshareholdersequity,noncurrentliabilities,totalnoncurrentliabilities,131638,145129,148101,162431
21,liabilitiesandshareholdersequity,shareholdersequity,commonstockandadditionalpaidincapital,83276,73812,64849,57365
22,liabilitiesandshareholdersequity,shareholdersequity,totalshareholdersequity,56950,62146,50672,63090
23,liabilitiesandshareholdersequity,totalliabilitiesandshareholdersequity,NaN,364980,352583,352755,351002

In [88]:
balance_sheet_df_2020 = balance_sheet_df_2020.applymap(clean_text)
balance_sheet_df_2018 = balance_sheet_df_2018.applymap(clean_text)

In [89]:
balance_sheet_df_2020

,item,category,subcategory,2020-09-26,2019-09-28
0,assets,currentassets,cashandcashequivalents,38016,48844
1,assets,currentassets,marketablesecurities,52927,51713
2,assets,currentassets,"accountsreceivable,net",16120,22926
3,assets,currentassets,inventories,4061,4106
4,assets,currentassets,vendornontradereceivables,21325,22878
5,assets,currentassets,othercurrentassets,11264,12352
6,assets,currentassets,totalcurrentassets,143713,162819
7,assets,noncurrentassets,marketablesecurities,100887,105341
8,assets,noncurrentassets,"property,plantandequipment,net",36766,37378
9,assets,noncurrentassets,othernoncurrentassets,42522,32978
10,assets,noncurrentassets,totalnoncurrentassets,180175,175697
11,assets,totalassets,NaN,323888,338516
12,liabilitiesandshareholdersequity,currentliabilities,accountspayable,42296,46236
13,liabilitiesandshareholdersequity,currentliabilities,othercurrentliabilities,42684,37720
14,liabilitiesandshareholdersequity,currentliabilities,deferredrevenue,6643,5522
15,liabilitiesandshareholdersequity,currentliabilities,commercialpaper,4996,5980
16,liabilitiesandshareholdersequity,currentliabilities,termdebt,8773,10260
17,liabilitiesandshareholdersequity,currentliabilities,totalcurrentliabilities,105392,105718
18,liabilitiesandshareholdersequity,noncurrentliabilities,termdebt,98667,91807
19,liabilitiesandshareholdersequity,noncurrentliabilities,othernoncurrentliabilities,54490,50503
20,liabilitiesandshareholdersequity,noncurrentliabilities,totalnoncurrentliabilities,153157,142310
21,liabilitiesandshareholdersequity,totalliabilities,NaN,258549,248028
22,liabilitiesandshareholdersequity,shareholdersequity,commonstockandadditionalpaidincapital,50779,45174
23,liabilitiesandshareholdersequity,shareholdersequity,retainedearnings,14966,45898
24,liabilitiesandshareholdersequity,shareholdersequity,accumulatedothercomprehensiveincome/(loss),-406,-584
25,liabilitiesandshareholdersequity,shareholdersequity,totalshareholdersequity,65339,90488
26,liabilitiesandshareholdersequity,totalliabilitiesandshareholdersequity,NaN,323888,338516

In [90]:
balance_sheet_df_2020.columns = balance_sheet_df_2020.columns.str.lower()
merged_balance_sheet_2 = pd.merge(merged_balance_sheet, balance_sheet_df_2020, 
                                on=['item', 'category', 'subcategory'], 
                                )

In [91]:
merged_balance_sheet_2

,item,category,subcategory,2024-09-28,2023-09-30,"september 24, 2022","september 25, 2021",2020-09-26,2019-09-28
0,assets,currentassets,cashandcashequivalents,29943,29965,23646,34940,38016,48844
1,assets,currentassets,marketablesecurities,35228,31590,2458,27699,52927,51713
2,assets,currentassets,vendornontradereceivables,32833,31477,32748,25228,21325,22878
3,assets,currentassets,inventories,7286,6331,4946,6580,4061,4106
4,assets,currentassets,othercurrentassets,14287,14695,21223,14111,11264,12352
5,assets,currentassets,totalcurrentassets,152987,143566,135405,134836,143713,162819
6,assets,noncurrentassets,marketablesecurities,91479,100544,120805,127877,100887,105341
7,assets,noncurrentassets,othernoncurrentassets,74834,64758,54428,48849,42522,32978
8,assets,noncurrentassets,totalnoncurrentassets,211993,209017,217350,216166,180175,175697
9,assets,totalassets,NaN,364980,352583,352755,351002,323888,338516
10,liabilitiesandshareholdersequity,currentliabilities,accountspayable,68960,62611,64115,54763,42296,46236
11,liabilitiesandshareholdersequity,currentliabilities,othercurrentliabilities,78304,58829,60845,47493,42684,37720
12,liabilitiesandshareholdersequity,currentliabilities,deferredrevenue,8249,8061,7912,7612,6643,5522
13,liabilitiesandshareholdersequity,currentliabilities,commercialpaper,9967,5985,9982,6000,4996,5980
14,liabilitiesandshareholdersequity,currentliabilities,termdebt,10912,9822,11128,9613,8773,10260
15,liabilitiesandshareholdersequity,currentliabilities,totalcurrentliabilities,176392,145308,153982,125481,105392,105718
16,liabilitiesandshareholdersequity,noncurrentliabilities,termdebt,85750,95281,98959,109106,98667,91807
17,liabilitiesandshareholdersequity,noncurrentliabilities,othernoncurrentliabilities,45888,49848,49142,53325,54490,50503
18,liabilitiesandshareholdersequity,noncurrentliabilities,totalnoncurrentliabilities,131638,145129,148101,162431,153157,142310
19,liabilitiesandshareholdersequity,shareholdersequity,commonstockandadditionalpaidincapital,83276,73812,64849,57365,50779,45174
20,liabilitiesandshareholdersequity,shareholdersequity,totalshareholdersequity,56950,62146,50672,63090,65339,90488
21,liabilitiesandshareholdersequity,totalliabilitiesandshareholdersequity,NaN,364980,352583,352755,351002,323888,338516